apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-dp
  labels:
    app: app-argocd
spec:
  selector:
    matchLabels:
      app: app-argocd
  replicas: 3
  template:
    metadata:
      labels:
        app: app-argocd
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: app1
        image: iad.ocir.io/idlhjo6dp3bd/argocd-aplication:1.0
        ports:
        - containerPort: 80
